-- Créer la base de données
CREATE DATABASE IF NOT EXISTS MY_GRP_LAB;

-- Se positionner dessus
USE DATABASE MY_GRP_LAB;

-- Créer les 3 schémas
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;


-- Créer le warehouse 
CREATE WAREHOUSE IF NOT EXISTS MY_GRP_WH
    WITH WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- L'activer
USE WAREHOUSE MY_GRP_WH;

-- Utilisateur Djaz
CREATE USER djaz
    PASSWORD        = 'MyGrp2026!'
    DEFAULT_ROLE    = SYSADMIN
    DEFAULT_WAREHOUSE = MY_GRP_WH
    DEFAULT_NAMESPACE = MY_GRP_LAB
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE SYSADMIN TO USER djaz;

-- Utilisateur Basma
CREATE USER basma
    PASSWORD        = 'MyGrp2026!'
    DEFAULT_ROLE    = SYSADMIN
    DEFAULT_WAREHOUSE = MY_GRP_WH
    DEFAULT_NAMESPACE = MY_GRP_LAB
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE SYSADMIN TO USER basma;

SHOW USERS;

-- Leur donner les rôles
GRANT ROLE SYSADMIN TO USER djaz;
GRANT ROLE SYSADMIN TO USER basma;

-- Leur donner accès à la database
GRANT USAGE ON DATABASE MY_GRP_LAB TO ROLE SYSADMIN;

-- Leur donner accès aux schémas
GRANT USAGE ON SCHEMA MY_GRP_LAB.BRONZE TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA MY_GRP_LAB.SILVER TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA MY_GRP_LAB.ANALYTICS TO ROLE SYSADMIN;

-- Leur donner accès aux tables (quand elles existeront)
GRANT ALL ON ALL TABLES IN SCHEMA MY_GRP_LAB.BRONZE TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA MY_GRP_LAB.SILVER TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA MY_GRP_LAB.ANALYTICS TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;

-- Donner le warehouse à SYSADMIN
GRANT USAGE ON WAREHOUSE MY_GRP_WH TO ROLE SYSADMIN;

-- Donner accès à la database
GRANT USAGE ON DATABASE MY_GRP_LAB TO ROLE SYSADMIN;

-- Donner accès aux schémas
GRANT USAGE ON SCHEMA MY_GRP_LAB.BRONZE    TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA MY_GRP_LAB.SILVER    TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA MY_GRP_LAB.ANALYTICS TO ROLE SYSADMIN;

-- Donner accès aux tables existantes ET futures
GRANT ALL ON ALL TABLES IN SCHEMA MY_GRP_LAB.BRONZE    TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA MY_GRP_LAB.SILVER    TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA MY_GRP_LAB.ANALYTICS TO ROLE SYSADMIN;

-- IMPORTANT : donner accès aux tables futures automatiquement
GRANT ALL ON FUTURE TABLES IN SCHEMA MY_GRP_LAB.BRONZE    TO ROLE SYSADMIN;
GRANT ALL ON FUTURE TABLES IN SCHEMA MY_GRP_LAB.SILVER    TO ROLE SYSADMIN;
GRANT ALL ON FUTURE TABLES IN SCHEMA MY_GRP_LAB.ANALYTICS TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;  -- ou SECURITYADMIN selon l'organisation

-- 1. Permissions sur le warehouse
GRANT USAGE ON WAREHOUSE MY_GRP_WH TO USER djaz;

-- 2. Permissions sur la base de données
GRANT USAGE ON DATABASE MY_GRP_LAB TO USER djaz;

-- 3. Permissions sur le schéma ANALYTICS (création de tables)
GRANT USAGE ON SCHEMA MY_GRP_LAB.ANALYTICS TO USER djaz;
GRANT CREATE TABLE ON SCHEMA MY_GRP_LAB.ANALYTICS TO USER djaz;
GRANT CREATE VIEW ON SCHEMA MY_GRP_LAB.ANALYTICS TO USER djaz;

-- Droits sur les tables existantes et futures dans ANALYTICS
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MY_GRP_LAB.ANALYTICS TO USER djaz;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MY_GRP_LAB.ANALYTICS TO USER djaz;

-- 4. Permissions de lecture sur le schéma SILVER (source des données)
GRANT USAGE ON SCHEMA MY_GRP_LAB.SILVER TO USER djaz;
GRANT SELECT ON ALL TABLES IN SCHEMA MY_GRP_LAB.SILVER TO USER djaz;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MY_GRP_LAB.SILVER TO USER djaz;

-- 5. Vérification (optionnel)
SHOW GRANTS TO USER djaz;
